# Generated by Django 3.2.4 on 2021-06-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_alter_clinica_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='dueño',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='horarios',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
