# Generated by Django 3.2.4 on 2021-06-24 16:09

import Veterinaria.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0003_auto_20210622_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Numeros])),
                ('nombreClinica', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras])),
                ('direccionClinica', models.CharField(max_length=300, validators=[Veterinaria.validators.solo_Letras])),
                ('horariosClinica', models.CharField(max_length=500)),
                ('telefonoClinica', models.CharField(help_text='####-####', max_length=10, validators=[Veterinaria.validators.solo_Numeros])),
                ('serviciosClinica', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='clinica',
            name='dueño',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nombre',
            field=models.CharField(max_length=60, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(max_length=9, validators=[Veterinaria.validators.solo_Numeros]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='color',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimPac',
            field=models.DateField(blank=True, validators=[Veterinaria.validators.validar_Fecha]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombrePac',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raza',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='dui',
            field=models.CharField(help_text='########-#', max_length=10, primary_key=True, serialize=False, validators=[Veterinaria.validators.solo_Numeros]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='edad',
            field=models.IntegerField(help_text='Se calculará automaticamente', validators=[Veterinaria.validators.solo_Numeros]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='fechaNacim',
            field=models.DateField(validators=[Veterinaria.validators.validar_Fecha]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(help_text='####-####', max_length=9, validators=[Veterinaria.validators.solo_Numeros]),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('duiEmp', models.CharField(help_text='########-#', max_length=10, primary_key=True, serialize=False, validators=[Veterinaria.validators.solo_Numeros])),
                ('nombreEmp', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras])),
                ('apellidoEmp', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras])),
                ('telefonoEmp', models.CharField(help_text='####-####', max_length=10, validators=[Veterinaria.validators.solo_Numeros])),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.CharField(max_length=9, validators=[Veterinaria.validators.solo_Numeros])),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.clinica')),
            ],
        ),
    ]
