# Generated by Django 3.2.4 on 2021-07-21 03:04

import Veterinaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_auto_20210624_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='direccionClinica',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitante',
            field=models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras]),
        ),
    ]
