# Generated by Django 3.2.4 on 2021-07-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_auto_20210720_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=5)),
                ('indicador', models.CharField(blank=True, choices=[('a', 'AM'), ('p', 'PM')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCita', models.DateField(null=True, verbose_name='Fecha de Cita')),
                ('pendiente', models.BooleanField(default=1, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('horaCita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.horario', verbose_name='Hora de Cita')),
                ('pacienteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.paciente')),
            ],
            options={
                'unique_together': {('fechaCita', 'horaCita')},
            },
        ),
    ]
