# Generated by Django 3.2.5 on 2021-07-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0005_auto_20210703_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='nombre',
            new_name='nombreClinica',
        ),
        migrations.RenameField(
            model_name='clinica',
            old_name='dueño',
            new_name='propietario',
        ),
        migrations.AddField(
            model_name='clinica',
            name='correoElectronico',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='fechaIngreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
