# Generated by Django 3.2.4 on 2021-07-23 01:13

import Veterinaria.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0006_cita_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fechaInscrip',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='personaInscrip',
            field=models.CharField(default=django.utils.timezone.now, max_length=70, validators=[Veterinaria.validators.solo_Letras]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='pendiente',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='horario',
            name='indicador',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], max_length=2),
        ),
    ]
