# Generated by Django 3.2.5 on 2021-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0006_auto_20210721_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nombreClinica',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
