# Generated by Django 3.2.5 on 2021-07-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0007_auto_20210721_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='nombreClinica',
            new_name='nombre',
        ),
    ]
