# Generated by Django 3.2.4 on 2021-07-23 05:07

import Veterinaria.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0008_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(null=True, validators=[Veterinaria.validators.fecha_mayor], verbose_name='Fecha de Cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='proximoCont',
            field=models.DateField(null=True, validators=[Veterinaria.validators.fecha_mayor]),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica')),
                ('pacienteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.paciente')),
            ],
        ),
    ]
