# Generated by Django 3.2.5 on 2021-07-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0008_rename_nombreclinica_clinica_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.TextField()),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('horarios', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('servicios', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField(auto_now_add=True, null=True)),
                ('correoElectronico', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.clinica')),
            ],
        ),
    ]
