# Generated by Django 3.2.4 on 2021-07-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0009_auto_20210722_2307'),
        ('Veterinaria', '0009_consultorio'),
    ]

    operations = [
    ]
