# Generated by Django 3.2.4 on 2021-08-04 18:13

import Veterinaria.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0010_merge_0009_auto_20210722_2307_0009_consultorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=50)),
                ('descServicio', models.CharField(max_length=200)),
                ('catServicio', models.CharField(max_length=30)),
                ('estadoServicio', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='pendiente',
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='servicios',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='telefono',
            field=models.CharField(max_length=9, validators=[Veterinaria.validators.formato_Telefono]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='duiEmp',
            field=models.CharField(help_text='########-#', max_length=10, primary_key=True, serialize=False, validators=[Veterinaria.validators.formato_Dui], verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefonoEmp',
            field=models.CharField(help_text='####-####', max_length=10, validators=[Veterinaria.validators.formato_Telefono]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='dui',
            field=models.CharField(help_text='########-#', max_length=10, primary_key=True, serialize=False, validators=[Veterinaria.validators.formato_Dui]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(help_text='####-####', max_length=9, validators=[Veterinaria.validators.formato_Telefono]),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='telefonoClinica',
            field=models.CharField(help_text='####-####', max_length=10, validators=[Veterinaria.validators.formato_Telefono]),
        ),
        migrations.AddField(
            model_name='clinica',
            name='servicios',
            field=models.ManyToManyField(to='Veterinaria.Servicio'),
        ),
    ]
