# Generated by Django 3.2.4 on 2021-08-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_auto_20210804_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.servicio'),
            preserve_default=False,
        ),
    ]
