# Generated by Django 3.2.5 on 2021-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_auto_20210804_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='consultorio',
            name='servicios',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='servicios',
            field=models.ManyToManyField(to='Veterinaria.Servicio'),
        ),
    ]
