# Generated by Django 3.2.4 on 2021-08-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0012_auto_20210804_1248'),
        ('Veterinaria', '0012_cita_servicio'),
    ]

    operations = [
    ]
