# Generated by Django 3.2.6 on 2021-08-06 09:37

import Veterinaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0013_merge_0012_auto_20210804_1248_0012_cita_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras])),
                ('nombreClinica', models.CharField(max_length=100, validators=[Veterinaria.validators.solo_Letras])),
                ('nombreServicio', models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras])),
                ('razonSolicitud', models.CharField(max_length=200)),
                ('catSolicitud', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreServicio',
            field=models.CharField(max_length=50, validators=[Veterinaria.validators.solo_Letras]),
        ),
    ]
