# Generated by Django 3.2.6 on 2021-08-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0015_servicio_activoservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='activoServicio',
        ),
    ]
