# Generated by Django 3.2.4 on 2021-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0016_remove_servicio_activoservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ManyToManyField(to='Veterinaria.Servicio'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.CharField(help_text=' Formato de Hora: ##:##', max_length=5),
        ),
    ]
