# Generated by Django 3.2.4 on 2021-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0018_auto_20211002_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
